// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

/**
 * @constructor
 */
export class Utf8View {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos = 0;
  /**
   * @param number i
   * @param flatbuffers.ByteBuffer bb
   * @returns Utf8View
   */
  __init(i:number, bb:flatbuffers.ByteBuffer):Utf8View {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  };

  /**
   * @param flatbuffers.ByteBuffer bb
   * @param Utf8View= obj
   * @returns Utf8View
   */
  static getRootAsUtf8View(bb:flatbuffers.ByteBuffer, obj?:Utf8View):Utf8View {
    return (obj || new Utf8View).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  };

  /**
   * @param flatbuffers.Builder builder
   */
  static startUtf8View(builder:flatbuffers.Builder) {
    builder.startObject(0);
  };

  /**
   * @param flatbuffers.Builder builder
   * @returns flatbuffers.Offset
   */
  static endUtf8View(builder:flatbuffers.Builder):flatbuffers.Offset {
    var offset = builder.endObject();
    return offset;
  };

  static createUtf8View(builder:flatbuffers.Builder):flatbuffers.Offset {
    Utf8View.startUtf8View(builder);
    return Utf8View.endUtf8View(builder);
  }
}